name: expense_tracker_app
description: "A new Flutter project."
publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: ^3.9.2

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.8
  flutter_riverpod: ^3.0.3
  sqflite: ^2.4.2
  path: ^1.9.1
  path_provider: ^2.1.5
  flutter_local_notifications: ^19.5.0
  local_auth: ^2.3.0
  shared_preferences: ^2.5.3
  flutter_screenutil: ^5.9.3
  google_fonts: ^6.3.2
  flutter_slidable: ^4.0.3
  intl: ^0.20.2
  dropdown_button2: ^2.3.9
  flutter_launcher_icons: ^0.14.4
  overlay_support: ^2.1.0
  fl_chart: ^1.1.1
  timezone: ^0.10.1
  flutter_timezone: ^4.1.1
  flutter_secure_storage: ^9.2.4
  flutter_colorpicker: ^1.1.0
  csv: ^6.0.0
  open_file: ^3.5.10
  permission_handler: ^12.0.1
  file_picker: ^10.3.7

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0

flutter_launcher_icons:
  android: true
  ios: true
  image_path: "assets/transparent.png"


flutter:
  uses-material-design: true
  assets:
    - assets/icon.png
    - assets/transparent.png
